server:
  port: 2221

spring:
  application:
    name: eureka-product-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/     # 指定注册中心地址
  instance:
    preferIpAdress:
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
